version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"
    volumes:
      - ./data/pgadmin/
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "monnerat@monnerat.com.br"
      PGADMIN_DEFAULT_PASSWORD: "abc"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge
